version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - composercache:/.composer
    environment:
      - APP_ENV=local
    links:
      - database
  database:
    image: mariadb:latest
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ms_bolton
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 1nf3rn4l
  phpqa:
    image: jakzal/phpqa:php7.1-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - "database:db"
volumes:
  database:
  composercache:
